"""UProject Launcher translations."""

from framekit.localization import register_translations


register_translations({
    "en": {
        "uproject_launcher": "UProject Launcher",
        "local_profile": "Launch profile",
        "profile_path": "Path to .ulaunch profile...",
        "new_profile": "New Profile",
        "project_path": "Project",
        "project_path_hint": "Empty: use a .uproject with the same name as the profile",
        "project_path_placeholder": "Absolute or profile-relative .uproject path...",
        "engine": "Engine",
        "engine_path_placeholder": "Engine root path or registered version...",
        "engine_path_hint": "Can be entered manually or filled from the project's EngineAssociation",
        "auto_detect": "Auto Detect",
        "auto_detect_failed": "Could not detect project and engine:\n{error}",
        "engine_unresolved": "Engine is not resolved",
        "local_plugins": "Local plugins",
        "scan_plugins": "Scan Plugins...",
        "remove_plugin": "Remove",
        "enabled": "Enabled",
        "plugin_name": "Name",
        "plugin_id": "Plugin",
        "plugin_version": "Version",
        "plugin_author": "Author",
        "plugin_description": "Description",
        "additional_arguments": "Additional command-line arguments",
        "additional_arguments_hint": "For example: -log -NoSplash",
        "save_profile": "Save",
        "launch_project": "Launch Project",
        "select_profile": "Select a .ulaunch profile",
        "create_profile": "Create a .ulaunch profile",
        "profile_filter": "UProject Launch Profile (*.ulaunch)",
        "project_filter": "Unreal Project (*.uproject)",
        "profile_saved": "Profile saved",
        "profile_save_failed": "Could not save profile:\n{error}",
        "profile_load_failed": "Could not open profile:\n{error}",
        "profile_required": "Open or create a .ulaunch profile first.",
        "project_unresolved": "Project could not be resolved:\n{error}",
        "engine_unresolved_error": "Engine could not be resolved:\n{error}",
        "plugin_scan_failed": "Could not scan engine plugins:\n{error}",
        "launch_failed": "Could not launch Unreal Editor:\n{error}",
        "project_launched": "Unreal Editor launched",
        "scan_plugins_title": "Engine Plugins",
        "filter_plugins": "Filter by name, author, version, or description...",
        "plugins_found": "{visible} of {total} plugins",
        "add_selected_plugins": "Apply Selection",
        "no_plugins": "No local plugins selected",
        "unsaved_profile": "Unsaved profile",
        "discard_changes": "Discard unsaved changes?",
        "command_preview": "Launch command",
    },
    "ru": {
        "uproject_launcher": "UProject Launcher",
        "local_profile": "Локальный профиль запуска",
        "profile_path": "Путь к профилю .ulaunch...",
        "new_profile": "Новый профиль",
        "project_path": "Проект",
        "project_path_hint": "Пусто: использовать .uproject с тем же именем, что у профиля",
        "project_path_placeholder": "Абсолютный или относительный от профиля путь к .uproject...",
        "engine": "Движок",
        "engine_path_placeholder": "Путь к корню движка или зарегистрированная версия...",
        "engine_path_hint": "Можно указать вручную или заполнить из EngineAssociation проекта",
        "auto_detect": "Определить автоматически",
        "auto_detect_failed": "Не удалось определить проект и движок:\n{error}",
        "engine_unresolved": "Движок не определён",
        "local_plugins": "Локальные плагины",
        "scan_plugins": "Сканировать плагины...",
        "remove_plugin": "Удалить",
        "enabled": "Включён",
        "plugin_name": "Название",
        "plugin_id": "Плагин",
        "plugin_version": "Версия",
        "plugin_author": "Автор",
        "plugin_description": "Описание",
        "additional_arguments": "Дополнительные аргументы командной строки",
        "additional_arguments_hint": "Например: -log -NoSplash",
        "save_profile": "Сохранить",
        "launch_project": "Запустить проект",
        "select_profile": "Выберите профиль .ulaunch",
        "create_profile": "Создайте профиль .ulaunch",
        "profile_filter": "Профиль запуска UProject (*.ulaunch)",
        "project_filter": "Проект Unreal (*.uproject)",
        "profile_saved": "Профиль сохранён",
        "profile_save_failed": "Не удалось сохранить профиль:\n{error}",
        "profile_load_failed": "Не удалось открыть профиль:\n{error}",
        "profile_required": "Сначала откройте или создайте профиль .ulaunch.",
        "project_unresolved": "Не удалось определить проект:\n{error}",
        "engine_unresolved_error": "Не удалось определить движок:\n{error}",
        "plugin_scan_failed": "Не удалось просканировать плагины движка:\n{error}",
        "launch_failed": "Не удалось запустить Unreal Editor:\n{error}",
        "project_launched": "Unreal Editor запущен",
        "scan_plugins_title": "Плагины движка",
        "filter_plugins": "Фильтр по названию, автору, версии или описанию...",
        "plugins_found": "Показано {visible} из {total}",
        "add_selected_plugins": "Применить выбор",
        "no_plugins": "Локальные плагины не выбраны",
        "unsaved_profile": "Несохранённый профиль",
        "discard_changes": "Отменить несохранённые изменения?",
        "command_preview": "Команда запуска",
    },
})
