"""UProject Launcher translations."""

from framekit.localization import register_translations


register_translations({
    "en": {
        "uproject_launcher": "UProject Launcher",
        "local_profile": "Launch profile",
        "file_associations": "System",
        "associations_description": "Register .ulaunch profiles in Windows Explorer. Double-click launches the project; the classic context menu offers launch and editing.",
        "association_application": "Application",
        "association_executable_hint": "Path to UE Forge or UProject Launcher .exe...",
        "register_associations": "Register .ulaunch",
        "windows_default_apps": "Windows default apps",
        "associations_note": "Registration takes effect immediately for your Windows account. Register again if you move the application.",
        "associations_registered": "Registered. Double-click launches the project.",
        "associations_choose_default": "Registered. In Windows default apps, find .ulaunch and choose UE Forge UProject Launcher to make launch the default action.",
        "associations_not_registered": ".ulaunch integration is not registered or needs updating.",
        "associations_windows_only": "File registration is available on Windows.",
        "association_failed": "Could not register file associations:\n{error}",
        "edit_launch_profile": "Edit profile",
        "profile_path": "Path to .ulaunch profile...",
        "drop_launch_profile": "Drop .ulaunch profile to open",
        "drop_launch_profile_invalid": "Drop one .ulaunch file",
        "new_profile": "New Profile",
        "project_path": "Project",
        "project_path_hint": "Empty: use a .uproject with the same name as the profile",
        "project_path_placeholder": "Absolute or profile-relative .uproject path...",
        "engine": "Engine",
        "engine_path_placeholder": "Engine root path or registered version...",
        "engine_path_hint": "Can be entered manually or filled from the project's EngineAssociation",
        "auto_detect": "Auto Detect",
        "auto_detect_failed": "Could not detect project and engine:\n{error}",
        "engine_unresolved": "Engine is not resolved",
        "local_plugins": "Local plugins",
        "scan_plugins": "Scan Plugins...",
        "remove_plugin": "Remove",
        "enabled": "Enabled",
        "plugin_name": "Name",
        "plugin_id": "Plugin",
        "plugin_version": "Version",
        "plugin_author": "Author",
        "plugin_description": "Description",
        "additional_arguments": "Additional command-line arguments",
        "additional_arguments_hint": "For example: -log -NoSplash",
        "save_profile": "Save",
        "launch_project": "Launch Project",
        "select_profile": "Select a .ulaunch profile",
        "create_profile": "Create a .ulaunch profile",
        "profile_filter": "UProject Launch Profile (*.ulaunch)",
        "project_filter": "Unreal Project (*.uproject)",
        "profile_saved": "Profile saved",
        "profile_save_failed": "Could not save profile:\n{error}",
        "profile_load_failed": "Could not open profile:\n{error}",
        "profile_required": "Open or create a .ulaunch profile first.",
        "project_unresolved": "Project could not be resolved:\n{error}",
        "engine_unresolved_error": "Engine could not be resolved:\n{error}",
        "plugin_scan_failed": "Could not scan engine plugins:\n{error}",
        "launch_failed": "Could not launch Unreal Editor:\n{error}",
        "project_launched": "Unreal Editor launched",
        "scan_plugins_title": "Engine Plugins",
        "filter_plugins": "Filter by name, author, version, or description...",
        "plugins_found": "{visible} of {total} plugins",
        "add_selected_plugins": "Apply Selection",
        "no_plugins": "No local plugins selected",
        "unsaved_profile": "Unsaved profile",
        "discard_changes": "Discard unsaved changes?",
        "command_preview": "Launch command",
    },
    "ru": {
        "uproject_launcher": "UProject Launcher",
        "local_profile": "Локальный профиль запуска",
        "file_associations": "Система",
        "associations_description": "Регистрация профилей .ulaunch в Проводнике Windows. Двойной щелчок запускает проект; классическое контекстное меню содержит запуск и редактирование.",
        "association_application": "Приложение",
        "association_executable_hint": "Путь к .exe UE Forge или UProject Launcher...",
        "register_associations": "Зарегистрировать .ulaunch",
        "windows_default_apps": "Приложения по умолчанию",
        "associations_note": "Регистрация действует сразу для вашей учётной записи Windows. Если переместите приложение, зарегистрируйте его заново.",
        "associations_registered": "Зарегистрировано. Двойной щелчок запускает проект.",
        "associations_choose_default": "Зарегистрировано. В приложениях Windows по умолчанию найдите .ulaunch и выберите UE Forge UProject Launcher, чтобы запуск стал действием по умолчанию.",
        "associations_not_registered": "Регистрация .ulaunch отсутствует или требует обновления.",
        "associations_windows_only": "Регистрация файлов доступна в Windows.",
        "association_failed": "Не удалось зарегистрировать ассоциации файлов:\n{error}",
        "edit_launch_profile": "Редактировать профиль",
        "profile_path": "Путь к профилю .ulaunch...",
        "drop_launch_profile": "Перетащите профиль .ulaunch для открытия",
        "drop_launch_profile_invalid": "Перетащите один файл .ulaunch",
        "new_profile": "Новый профиль",
        "project_path": "Проект",
        "project_path_hint": "Пусто: использовать .uproject с тем же именем, что у профиля",
        "project_path_placeholder": "Абсолютный или относительный от профиля путь к .uproject...",
        "engine": "Движок",
        "engine_path_placeholder": "Путь к корню движка или зарегистрированная версия...",
        "engine_path_hint": "Можно указать вручную или заполнить из EngineAssociation проекта",
        "auto_detect": "Определить автоматически",
        "auto_detect_failed": "Не удалось определить проект и движок:\n{error}",
        "engine_unresolved": "Движок не определён",
        "local_plugins": "Локальные плагины",
        "scan_plugins": "Сканировать плагины...",
        "remove_plugin": "Удалить",
        "enabled": "Включён",
        "plugin_name": "Название",
        "plugin_id": "Плагин",
        "plugin_version": "Версия",
        "plugin_author": "Автор",
        "plugin_description": "Описание",
        "additional_arguments": "Дополнительные аргументы командной строки",
        "additional_arguments_hint": "Например: -log -NoSplash",
        "save_profile": "Сохранить",
        "launch_project": "Запустить проект",
        "select_profile": "Выберите профиль .ulaunch",
        "create_profile": "Создайте профиль .ulaunch",
        "profile_filter": "Профиль запуска UProject (*.ulaunch)",
        "project_filter": "Проект Unreal (*.uproject)",
        "profile_saved": "Профиль сохранён",
        "profile_save_failed": "Не удалось сохранить профиль:\n{error}",
        "profile_load_failed": "Не удалось открыть профиль:\n{error}",
        "profile_required": "Сначала откройте или создайте профиль .ulaunch.",
        "project_unresolved": "Не удалось определить проект:\n{error}",
        "engine_unresolved_error": "Не удалось определить движок:\n{error}",
        "plugin_scan_failed": "Не удалось просканировать плагины движка:\n{error}",
        "launch_failed": "Не удалось запустить Unreal Editor:\n{error}",
        "project_launched": "Unreal Editor запущен",
        "scan_plugins_title": "Плагины движка",
        "filter_plugins": "Фильтр по названию, автору, версии или описанию...",
        "plugins_found": "Показано {visible} из {total}",
        "add_selected_plugins": "Применить выбор",
        "no_plugins": "Локальные плагины не выбраны",
        "unsaved_profile": "Несохранённый профиль",
        "discard_changes": "Отменить несохранённые изменения?",
        "command_preview": "Команда запуска",
    },
})
